const CURRENTLY_PLAYING_ENDPOINT = process.env.NEXT_PUBLIC_CURRENTLY_PLAYING_ENDPOINT!;
const RECENTLY_PLAYED_ENDPOINT = process.env.NEXT_PUBLIC_RECENTLY_PLAYED_ENDPOINT!;
const LEAVE_MESSAGE_ENDPOINT = process.env.NEXT_PUBLIC_LEAVE_MESSAGE_ENDPOINT!;

export {
	CURRENTLY_PLAYING_ENDPOINT,
	RECENTLY_PLAYED_ENDPOINT,
	LEAVE_MESSAGE_ENDPOINT
}