const CURRENTLY_PLAYING_ENDPOINT = '/api/spotify/currently-playing';
const RECENTLY_PLAYED_ENDPOINT = '/api/spotify/recently-played';
const LEAVE_MESSAGE_ENDPOINT = process.env.NEXT_PUBLIC_LEAVE_MESSAGE_ENDPOINT!;

export {
	CURRENTLY_PLAYING_ENDPOINT,
	RECENTLY_PLAYED_ENDPOINT,
	LEAVE_MESSAGE_ENDPOINT
}